apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: lesson2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx:1.19.2
        imagePullPolicy: IfNotPresent
        name: nginx
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        lifecycle:
          postStart:
            exec:
              command: ["sleep", "10"]
          preStop:
            exec:
              command: ["sleep", "30"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  ports:
    - name: web
      port: 80
#      targetPort: 80
    - name: multitool
      port: 8080
#      targetPort: 8080
  selector:
    app: myapp
  type: ClusterIP
