apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.20
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-labeled
  labels:
    rap: eminem
    rock: megadeth
    alternative: limp_bizkit
spec:
  containers:
    - name: nginx
      image: nginx:1.20
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-node-selector
  annotations:
    work-only: "will run on node with label 'gpu=true'"
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: nginx
      image: nginx:1.20