apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: pod-nginx2
spec:
  containers:
    - name: nginx
      image: nginx:1.18

---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx2
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: nginx
