apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool
  name: pod-multitool2
spec:
  containers:
    - name: network-multitool
      image: wbitt/network-multitool
      env:
        - name: HTTP_PORT
          value: "31080"
      ports:
        - containerPort: 31080
          name: somename
---
apiVersion: v1
kind: Service
metadata:
  name: svc-multitool2
spec:
  ports:
    - name: multitool-http
      protocol: TCP
      port: 80
      targetPort: somename
  selector:
    app: multitool