apiVersion: v1
kind: Pod
metadata:
  name: pod-init
  namespace: lesson2
spec:
  containers:
    - name: run-nginx
      image: nginx:1.20
  initContainers:
    - name: init-delay
      image: busybox
      command: [ 'sleep', '15' ]
