apiVersion: v1
kind: Pod
metadata:
  name: pod-readiness
  namespace: lesson2
  labels:
    app: nginx-readiness
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    env:
      - name: HTTP_PORT
        value: "31080"
    ports:
      - containerPort: 31080
        name: somename
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3  # wait 3 sec before run probe
      periodSeconds: 3        # period exec 3 sec
      timeoutSeconds: 1       # wait 1 sec after exec
      failureThreshold: 1     # 4
      successThreshold: 2     # after 2 success answer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-readiness
  namespace: lesson2
spec:
  ports:
    - port: 80
      targetPort: 31080
  selector:
    app: nginx-readiness