apiVersion: v1
kind: Pod
metadata:
  name: pod-multitool
  namespace: lesson3
spec:
  containers:
    - name: network-multitool
      image: wbitt/network-multitool
## https://github.com/wbitt/Network-MultiTool