apiVersion: v1
kind: Pod
metadata:
  name: pod-manual-pv
  namespace: lesson6
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-manual
