apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: lesson6
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/local"
          name: my-volume
        - mountPath: "/nfs"
          name: ext-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-manual
    - name: ext-volume
      persistentVolumeClaim:
        claimName: pvc-ext