---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: netology.dens-al.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nginx-simple
                port:
                  name: web
          - path: /app # http://microk8s.dens-al.ru/app -> http://svc-multitool/
            pathType: Exact
            backend:
              service:
                name: svc-multitool
                port:
                  name: app
#    - host: another.dens-al.ru
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: svc-nginx-blue
#                port:
#                  name: web
#    - host: example.dens-al.ru
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: svc-nginx-green
#                port:
#                  name: web