apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: lesson7
data:
  key1: "Hello netology guys!"
  key3: value02
  key2: |
    Test
    multiple lines
    more lines blablbalbalba
    some more lines
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: lesson7
type: Opaque
data:
  username: YWRtaW4K #YWRtaW4K # admin
  password: bmV0b2xvZ3kK # netology
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret2
  namespace: lesson7
data:
  username: aGVsbG8K #YWRtaW4K # admin
  password: bmV0b2xvZ3kK # netology