apiVersion: v1
kind: Pod
metadata:
  name: multitool-vol
  namespace: lesson7
spec:
  containers:
    - image: wbitt/network-multitool
      name: multitool
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config/config
        - name: secret-volume
          mountPath: /etc/config/secret
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap
    - name: secret-volume
      secret:
        secretName: my-secret