apiVersion: v1
kind: Pod
metadata:
  name: multitool-env
  namespace: lesson7
spec:
  containers:
    - image: wbitt/network-multitool
      name: multitool
      env:
        - name: CONFIGVAR1
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: key1
        - name: CONFIGVAR2
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: key2
        - name: SECRETVAR
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
      envFrom:
        - configMapRef:
            name: my-configmap