#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  namespace: metallb-system
#  name: config
#data:
#  config: |
#    address-pools:
#    - name: default
#      protocol: layer2
#      addresses:
#      - 185.231.155.97/32
#      - 109.107.176.177/32
#      - 77.246.97.66/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-pool
  namespace: metallb-system
spec:
  addresses:
    - 185.231.155.97/32
    - 95.142.47.111/32
    - 185.231.153.100/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-my-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - my-pool