apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: canary.dens-al.ru
  dnsNames:
  - canary.dens-al.ru