apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: externaldns
    meta.helm.sh/release-namespace: external-dns
  creationTimestamp: "2024-03-15T13:35:10Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: externaldns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/version: 0.5.0
    helm.sh/chart: externaldns-0.5.0
  name: externaldns
  namespace: external-dns
  resourceVersion: "16339"
  uid: ffc74da9-8e3d-457a-a063-e0cf8041b459
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: external-dns
    spec:
      containers:
      - args:
        - --txt-owner-id=external-dns
        - --source=service
        - --source=ingress
        - --provider=yandex
        - --yandex-folder=b1gjs8fcsfkd19lv51g0
        - --yandex-iam-key-file=/etc/kubernetes/iamkeyfile.json
        - --txt-prefix=external-dns-
        image: cr.yandex/yc-marketplace/yandex-cloud/externaldns/externaldns:0.5.0
        imagePullPolicy: IfNotPresent
        name: external-dns
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: yandex-iam-key-file
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: externaldns
      serviceAccountName: externaldns
      terminationGracePeriodSeconds: 30
      volumes:
      - name: yandex-iam-key-file
        secret:
          defaultMode: 420
          items:
          - key: iamkeyfile.json
            path: iamkeyfile.json
          secretName: externaldns
