apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: myapp

  source:
    repoURL: https://github.com/dens-al/k8s-study.git
    targetRevision: main
    path: 99-bonus/argocd/demo-helm/app

    helm:
      parameters:
      - name: "service.port"
        value: "8082"
      - name: "replicaCount"
        value: "4"
#      valueFiles:
#      - values-dev.yaml
#      values: |
#        # replicaCount: 2
#        serviceAccount:
#          create: true
#          annotations:
#            demo/role: demo-annotation
#          name: sa-custom-name

  destination:
    server: https://kubernetes.default.svc
    namespace: my-super-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
