apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: yc-secret-store # name of secret store
    kind: ClusterSecretStore # or SecretStore
  target:
    name: my-k8s-secret # new name that will be created in k8s secrets
  data:
  - secretKey: my-k8s-key
    remoteRef:
      key: e6qq17tt3cerrl0jc46g # идентификатор_секрета
      property: token