apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: yc-secret-store # name of secret store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          namespace: eso
          name: sa-creds # name of secret
          key: key # key, which value consists of auth information