apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: lesson2
spec:
  containers:
    - name: run-nginx
      image: nginx:1.20
  initContainers:
    - name: init-delay
      image: busybox
      command: [ 'sleep', '30' ]
#     command: [ 'sh', '-c', 'sleep 5 && echo "creating dir" && mkdir -p opt/log && echo test > ', '30' ]
