apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod-cmd
  namespace: lesson2
spec:
  containers:
  - name: nginx
    image: nginx:1.9
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3  # wait 3 sec before run probe
      periodSeconds: 3        # period exec 3 sec
      timeoutSeconds: 1       # wait 1 sec after exec
      failureThreshold: 4     # 4 attempts | if not working getting out from LB
      successThreshold: 2     # after 2 success answer