apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-cmd
  namespace: lesson2
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5  # wait 3 sec before run probe
      periodSeconds: 3        # period exec 3 sec
      timeoutSeconds: 1       # wait 1 sec after exec
      failureThreshold: 4     # 4 attempts
      successThreshold: 1     # after 2 success answer
