apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main
  name: nginx-recreate
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - image: nginx:1.21
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          name: main
          imagePullPolicy: IfNotPresent
