apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-multitool
  namespace: lesson3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: multitool

---
apiVersion: v1
kind: Service
metadata:
  name: dpl-multitool-svc
  namespace: default
spec:
  ports:
    - name: web
      port: 80
#      targetPort: 80
    - name: multitool
      port: 8080
#      targetPort: 8080
  selector:
    app: myapp
  type: ClusterIP
