apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: lesson3
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: myapp
#  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  namespace: lesson3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent