apiVersion: v1
kind: Service
metadata:
  name: svc-multitool-nodeport
  namespace: lesson3
spec:
#  sessionAffinity: ClientIP
  ports:
    - name: http-multitool
      port: 80
#      nodePort: 30080 # port-range: 30000-32767
      targetPort: 31080
  selector:
    app: nodeapp
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-multitool-nodeport
  namespace: lesson3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "31080"
