apiVersion: v1
kind: Service
metadata:
  name: svc-multitool-lb
  namespace: lesson3
spec:
  ports:
    - name: web
      port: 80
      targetPort: 31080
  selector:
    app: lbapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-multitool-lb
  namespace: lesson3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lbapp
  template:
    metadata:
      labels:
        app: lbapp
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "31080"