apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb
#  namespace: lesson3
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
#  namespace: lesson3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app
        image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent