apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
  namespace: lesson4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: nginx:1.19.2
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: lesson4
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: web