apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multitool
  namespace: lesson4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          name: multitool
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: lesson4
spec:
  ports:
    - name: app
      port: 80
  selector:
    app: myapp
