apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-bgc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: quay.io/rhdevelopers/blue-green-canary
          name: blue
          env:
            - name: BLUE_GREEN_CANARY_COLOR
              value: "#6bbded"
            - name: BLUE_GREEN_CANARY_MESSAGE
              value: "Hello"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: myapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dens-al.pro
      http:
        paths:
          - path: /bgc
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  name: web
#                port:
#                  name: web
#          - path: /app
#            pathType: Prefix
#            backend:
#              service:
#                name: app-svc
#                port:
#                  name: app

#  tls:
#    - hosts:
#        - ingress.almuhametov.ru
#      secretName: tls-secret
