apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      initContainers:
      - name: web-content
        image: busybox
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=green>GREEN</font></h1>" > /webdata/index.html']
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: webdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-green
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: nginx-green