apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          name: multitool