apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
  namespace: lesson5
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
#      volumeMounts:
#        - mountPath: "/tmp/cache"
#          name: my-volume
  volumes:
    - name: my-volume
      emptyDir: {}
