apiVersion: v1
kind: Pod
metadata:
  name: pod-manual-pv
  namespace: lesson6
spec:
  nodeSelector:
    gpu: "false"
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manual
  namespace: lesson6
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Mi
  hostPath:
    path: /data/pv
  persistentVolumeReclaimPolicy: Delete


# truncate -s 2M ostechnix.txt
# dd if=/dev/zero of=output.dat  bs=2M  count=1