apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: lesson6
spec:
#  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: local-nginx
  namespace: lesson6
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html