apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manual
  namespace: lesson6
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
