apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yc-pvc
  namespace: lesson6
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
    limits:
      1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: yc-nginx
  namespace: lesson6
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: yc-pvc
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc
          mountPath: /data