---
apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-ubuntu-dynamic
  namespace: lesson6
spec:
  containers:
  - name: csi-s3-test-ubuntu
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "for i in {1..10}; do echo $(date -u) >> /data/s3-dynamic/dynamic-date.txt; sleep 10; done"]
    volumeMounts:
      - mountPath: /data/s3-dynamic
        name: s3-volume
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: csi-s3-pvc-dynamic
        readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc-dynamic
  namespace: lesson6
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: csi-s3
